---
spring:
    config.activate.on-profile: default
cds:
    # odata-v4.endpoint.path: "/api"
    odataV4.endpoint.path: "/api"
    query.limit.default: 50
    query.limit.max: 50

---
spring:
  config.activate.on-profile: memory
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1
